import type { ApprovedInvoiceView } from '../../domain/approvedInvoiceView.js';

export function createApprovedInvoicePdfSample(): ApprovedInvoiceView {
  return {
    id: 'invoice-sample-1',
    companyId: 'dev-company',
    sourceDraftId: 'draft-sample-1',
    invoiceNumber: '24389',
    referenceNumber: '2438901007',
    referenceNumberType: 'finnishDomestic',
    seriesKey: 'default',
    sequenceScope: 'calendar-year:2026',
    sequenceNumber: 24_389,
    numberingMode: 'calendarYearSequence',
    status: 'approved',
    customerId: 'customer-housing-company',
    customerNumberSnapshot: '100',
    customerNameSnapshot: 'Asunto Oy Esimerkkitalo',
    customerBusinessIdSnapshot: '1234567-8',
    customerTypeSnapshot: 'housingCompany',
    customerEmailSnapshot: 'hallitus@example.fi',
    customerPhoneSnapshot: '040 111 2222',
    customerStreetAddressSnapshot: 'Taloyhtiönkatu 4',
    customerPostalCodeSnapshot: '20100',
    customerCitySnapshot: 'Turku',
    companyNameSnapshot: 'EKY-Rakenne Oy',
    companyBusinessIdSnapshot: '0970796-9',
    companyVatNumberSnapshot: 'FI09707969',
    companyStreetAddressSnapshot: 'Isovuorentie 310',
    companyPostalCodeSnapshot: '21290',
    companyCitySnapshot: 'Rusko',
    companyEmailSnapshot: 'eky@dnainternet.net',
    companyPhoneSnapshot: '0400647500',
    companyIbanSnapshot: 'FI8554714001000000',
    companyBicSnapshot: 'POPFFI22',
    companyBankNameSnapshot: 'POP Pankki',
    billingRecipientCustomerId: 'customer-property-manager',
    billingRecipientCustomerNumberSnapshot: '100',
    billingRecipientNameSnapshot: 'Isännöinti Äyräs Oy',
    billingRecipientBusinessIdSnapshot: '8765432-1',
    billingRecipientCustomerTypeSnapshot: 'propertyManager',
    billingRecipientEmailSnapshot: 'isannointi@example.fi',
    billingRecipientPhoneSnapshot: '040 333 4444',
    billingRecipientStreetAddressSnapshot: 'Isännöitsijänkatu 5',
    billingRecipientPostalCodeSnapshot: '20500',
    billingRecipientCitySnapshot: 'Turku',
    invoiceDate: '2026-07-03',
    dueDate: '2026-07-17',
    paymentTermDays: 14,
    reminderPeriodDays: 8,
    latePaymentInterestBasisPoints: 1300,
    priceInputMode: 'gross',
    subject: 'Liesituulettimen poistoilmaventtiilin muutostyöt',
    orderNumber: '',
    note: '',
    deliveryAddressText: 'Asunto Oy Esimerkkitalo, ovi 12, työt 7. ja 10.11.',
    lines: [
      {
        id: 'line-1',
        lineOrder: 1,
        code: '',
        description:
          'Liesituulettimen poistoilmaventtiilin tarvikehaku ja muutostyöt, tarvikkeiden sovitus sekä käyttöönottotarkistus',
        quantityHundredths: 700,
        unit: 'h',
        unitPriceCents: 5650,
        vatRateBasisPoints: 2550,
        discount: { type: 'none' },
        baseCents: 39_550,
        discountCents: 0,
        netCents: 31_514,
        vatCents: 8_036,
        grossCents: 39_550,
      },
      {
        id: 'line-2',
        lineOrder: 2,
        code: '',
        description: 'Kiinnityskehys',
        quantityHundredths: 100,
        unit: 'kpl',
        unitPriceCents: 795,
        vatRateBasisPoints: 2550,
        discount: { type: 'none' },
        baseCents: 795,
        discountCents: 0,
        netCents: 633,
        vatCents: 162,
        grossCents: 795,
      },
      {
        id: 'line-3',
        lineOrder: 3,
        code: '',
        description: 'Poistoilmaventtiili',
        quantityHundredths: 100,
        unit: 'kpl',
        unitPriceCents: 1650,
        vatRateBasisPoints: 2550,
        discount: { type: 'none' },
        baseCents: 1_650,
        discountCents: 0,
        netCents: 1_315,
        vatCents: 335,
        grossCents: 1_650,
      },
      {
        id: 'line-4',
        lineOrder: 4,
        code: '',
        description: 'IV sivuliitin',
        quantityHundredths: 100,
        unit: 'kpl',
        unitPriceCents: 595,
        vatRateBasisPoints: 2550,
        discount: { type: 'none' },
        baseCents: 595,
        discountCents: 0,
        netCents: 474,
        vatCents: 121,
        grossCents: 595,
      },
      {
        id: 'line-5',
        lineOrder: 5,
        code: '',
        description: 'IV ulkoliitin',
        quantityHundredths: 200,
        unit: 'kpl',
        unitPriceCents: 395,
        vatRateBasisPoints: 2550,
        discount: { type: 'none' },
        baseCents: 790,
        discountCents: 0,
        netCents: 629,
        vatCents: 161,
        grossCents: 790,
      },
      {
        id: 'line-6',
        lineOrder: 6,
        code: '',
        description: 'IV käyrä',
        quantityHundredths: 100,
        unit: 'kpl',
        unitPriceCents: 1050,
        vatRateBasisPoints: 2550,
        discount: { type: 'none' },
        baseCents: 1_050,
        discountCents: 0,
        netCents: 837,
        vatCents: 213,
        grossCents: 1_050,
      },
      {
        id: 'line-7',
        lineOrder: 7,
        code: '',
        description: 'Autokulut',
        quantityHundredths: 100,
        unit: 'kpl',
        unitPriceCents: 1000,
        vatRateBasisPoints: 2550,
        discount: { type: 'none' },
        baseCents: 1_000,
        discountCents: 0,
        netCents: 797,
        vatCents: 203,
        grossCents: 1_000,
      },
    ],
    totals: {
      netTotalCents: 36_199,
      vatTotalCents: 9_231,
      grossTotalCents: 45_430,
      vatBreakdown: [
        {
          vatRateBasisPoints: 2550,
          netCents: 36_199,
          vatCents: 9_231,
          grossCents: 45_430,
        },
      ],
    },
    vatBreakdown: [
      {
        vatRateBasisPoints: 2550,
        netCents: 36_199,
        vatCents: 9_231,
        grossCents: 45_430,
      },
    ],
    createdAt: '2026-07-03T10:00:00.000Z',
    approvedAt: '2026-07-03T10:15:00.000Z',
    updatedAt: '2026-07-03T10:15:00.000Z',
  };
}
