import type { InvoiceContentRevision } from '../domain/invoiceContentRevision.js';

type AuthoritativeRevision = Extract<
  InvoiceContentRevision,
  { vatBreakdownState: 'authoritative' }
>;

export function createInvoiceRevisionPdfContentFixture(): AuthoritativeRevision {
  return {
    companyId: 'synthetic-company',
    invoiceId: 'synthetic-invoice',
    revisionId: 'synthetic-revision',
    sourceDraftId: 'synthetic-draft',
    origin: 'approval',
    vatBreakdownState: 'authoritative',
    invoiceKind: 'standard',
    creditedInvoiceId: null,
    creditedRevisionId: null,
    creditedInvoiceNumberSnapshot: null,
    creditedInvoiceDateSnapshot: null,
    invoiceNumber: '20261001',
    referenceNumber: '202610010',
    referenceNumberType: 'finnishDomestic',
    seriesKey: 'default',
    sequenceScope: 'calendar-year:2026',
    sequenceNumber: 1001,
    numberingMode: 'calendarYearSequence',
    customerId: 'synthetic-customer',
    customerNumberSnapshot: 'C-001',
    customerNameSnapshot: 'Example Customer Oy',
    customerBusinessIdSnapshot: '1234567-8',
    customerTypeSnapshot: 'company',
    customerEmailSnapshot: 'customer@example.invalid',
    customerPhoneSnapshot: '010 000 0001',
    customerStreetAddressSnapshot: 'Test Customer Street 1',
    customerPostalCodeSnapshot: '00100',
    customerCitySnapshot: 'Test Customer City',
    companyNameSnapshot: 'Example Seller Oy',
    companyBusinessIdSnapshot: '2345678-9',
    companyVatNumberSnapshot: 'FI23456789',
    companyStreetAddressSnapshot: 'Test Seller Street 2',
    companyPostalCodeSnapshot: '00200',
    companyCitySnapshot: 'Test Seller City',
    companyEmailSnapshot: 'seller@example.invalid',
    companyPhoneSnapshot: '010 000 0002',
    companyWebsiteSnapshot: 'https://seller.example.invalid',
    companyIbanSnapshot: 'FI2112345600000785',
    companyBicSnapshot: 'NDEAFIHH',
    companyBankNameSnapshot: 'Example Bank',
    billingRecipientCustomerId: 'synthetic-recipient',
    billingRecipientCustomerNumberSnapshot: 'R-003',
    billingRecipientNameSnapshot: 'Example Recipient Oy',
    billingRecipientBusinessIdSnapshot: '3456789-0',
    billingRecipientCustomerTypeSnapshot: 'company',
    billingRecipientEmailSnapshot: 'recipient@example.invalid',
    billingRecipientPhoneSnapshot: '010 000 0003',
    billingRecipientStreetAddressSnapshot: 'Test Recipient Street 3',
    billingRecipientPostalCodeSnapshot: '00300',
    billingRecipientCitySnapshot: 'Test Recipient City',
    invoiceDate: '2026-10-01',
    dueDate: '2026-10-20',
    paymentTermDays: 14,
    reminderPeriodDays: 7,
    latePaymentInterestBasisPoints: 950,
    priceInputMode: 'net',
    subject: 'Not rendered by the current layout',
    orderNumber: 'ORDER-004',
    note: '  Snapshot note\nSecond line  ',
    deliveryAddressText: 'Test Site 5',
    refundIbanSnapshot: '',
    taxTreatment: 'normalVat',
    taxTreatmentLabelSnapshot: '',
    taxLegalBasisSnapshot: '',
    performanceDate: '2026-09-29',
    performancePeriodStart: null,
    performancePeriodEnd: null,
    totalNetCents: 104,
    totalVatCents: 15,
    totalGrossCents: 119,
    createdAt: '2026-10-01T10:00:00.000Z',
    approvedAt: '2026-10-01T10:05:00.000Z',
    lines: [
      {
        lineId: 'synthetic-line-1', invoiceId: 'synthetic-invoice',
        sourceInvoiceLineId: null, sourceRevisionId: null, lineOrder: 1,
        code: 'ITEM-1', description: 'Example item 1', quantityHundredths: 100,
        unit: 'kpl', unitPriceCents: 2, vatRateBasisPoints: 2550,
        discountType: 'none', discountValue: 0, baseCents: 2, discountCents: 0,
        netCents: 2, vatCents: 1, grossCents: 3,
        createdAt: '2026-10-01T10:05:00.000Z',
      },
      {
        lineId: 'synthetic-line-2', invoiceId: 'synthetic-invoice',
        sourceInvoiceLineId: null, sourceRevisionId: null, lineOrder: 2,
        code: 'ITEM-2', description: 'Example item 2', quantityHundredths: 100,
        unit: 'h', unitPriceCents: 2, vatRateBasisPoints: 2550,
        discountType: 'percentage', discountValue: 1000, baseCents: 2, discountCents: 0,
        netCents: 2, vatCents: 1, grossCents: 3,
        createdAt: '2026-10-01T10:05:00.000Z',
      },
      {
        lineId: 'synthetic-line-3', invoiceId: 'synthetic-invoice',
        sourceInvoiceLineId: null, sourceRevisionId: null, lineOrder: 3,
        code: 'ITEM-3', description: 'Example item 3', quantityHundredths: 100,
        unit: 'pak', unitPriceCents: 105, vatRateBasisPoints: 1350,
        discountType: 'fixed', discountValue: 5, baseCents: 105, discountCents: 5,
        netCents: 100, vatCents: 14, grossCents: 114,
        createdAt: '2026-10-01T10:05:00.000Z',
      },
    ],
    vatBreakdown: [
      { vatRateBasisPoints: 1350, netCents: 100, vatCents: 14, grossCents: 114 },
      { vatRateBasisPoints: 2550, netCents: 4, vatCents: 1, grossCents: 5 },
    ],
  };
}

export function createCreditRevisionPdfContentFixture(): AuthoritativeRevision {
  const revision = createInvoiceRevisionPdfContentFixture();
  return {
    ...revision,
    invoiceKind: 'credit',
    creditedInvoiceId: 'synthetic-source-invoice',
    creditedRevisionId: 'synthetic-source-revision',
    creditedInvoiceNumberSnapshot: '20260991',
    creditedInvoiceDateSnapshot: '2026-09-01',
    referenceNumber: null,
    referenceNumberType: null,
    dueDate: revision.invoiceDate,
    paymentTermDays: 0,
    reminderPeriodDays: 0,
    latePaymentInterestBasisPoints: 0,
    refundIbanSnapshot: 'FI2112345600000785',
    totalNetCents: 67,
    totalVatCents: 18,
    totalGrossCents: 85,
    lines: [{
      lineId: 'synthetic-credit-line', invoiceId: revision.invoiceId,
      sourceInvoiceLineId: 'synthetic-source-line',
      sourceRevisionId: 'synthetic-source-revision',
      lineOrder: 1, code: 'CREDIT-1', description: 'Example remaining credit',
      quantityHundredths: 100, unit: 'kpl', unitPriceCents: 67,
      vatRateBasisPoints: 2550, discountType: 'none', discountValue: 0,
      baseCents: 67, discountCents: 0, netCents: 67, vatCents: 18, grossCents: 85,
      createdAt: revision.approvedAt,
    }],
    vatBreakdown: [
      { vatRateBasisPoints: 2550, netCents: 67, vatCents: 18, grossCents: 85 },
    ],
  };
}
